version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: limit-barrier-app
    env_file:
      - .env
    environment:
      - REDIS_ADDR=redis:${REDIS_PORT}
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: limit-barrier-redis
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --port ${REDIS_PORT} --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - limit-barrier-volume:/data

volumes:
  limit-barrier-volume:
